apiVersion: apps/v1
kind: Deployment
metadata:
  name: aplicacao-deployment
  labels:
    app: alura-sports
spec:
  selector:
    matchLabels:
      app: alura-sports
  template:
    metadata:
      labels:
       app: alura-sports
    spec:
      containers:
        - name: container-aplicacao-loja
          image: alurasportsregistry.azurecr.io/loja/aplicacao-loja:v2
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: alurasportsregistry.secret

