apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:
      - secrets
      - configmaps
    providers:
      - aesgcm:
        keys:
          - name: key1
            secret: MKo7+2trZ5H1Fylc0qTrXGFgzRI8iGKhqCdxFRfoJ04=
      - identity: {}